allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sneat/*'
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - nx
  - unrs-resolver
