allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: false
  msgpackr-extract: false
  nx: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@sneat/*'
  - '@angular-eslint/builder@22.2.0'
  - '@angular-eslint/bundled-angular-compiler@22.2.0'
  - '@angular-eslint/eslint-plugin-template@22.2.0'
  - '@angular-eslint/eslint-plugin@22.2.0'
  - '@angular-eslint/schematics@22.2.0'
  - '@angular-eslint/template-parser@22.2.0'
  - '@angular-eslint/utils@22.2.0'
  - angular-eslint@22.2.0
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - less
  - nx
  - unrs-resolver
